version: '3.8'

services:
  debt-bot:
    build: .
    container_name: debt_manager_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"